language: node_js

cache:
  directories:
    - node_modules

branches:
   only:
      - master # will only build for master branch commits

node_js:
   - node # will use latest node

before_script: # commands to run before the build step
   - travis_retry npm install -g -dd @angular/cli
   - travis_retry npm install -g -dd firebase-tools # installs firebase to run firebase deploy

script: # the build step
   - test $TRAVIS_BRANCH != "master" && ng build --aot --prod --environment=q
   - test $TRAVIS_BRANCH = "master" && ng build --aot --prod --environment=p
after_success:
  - test $TRAVIS_BRANCH != "master" && firebase use q --token $FIREBASE_TOKEN --non-interactive
  - test $TRAVIS_BRANCH != "master" && firebase deploy --only hosting --token $FIREBASE_TOKEN --non-interactive # test build
  - test $TRAVIS_BRANCH = "master" && firebase use p --token $FIREBASE_TOKEN --non-interactive
  - test $TRAVIS_BRANCH = "master" && firebase deploy --only hosting --token $FIREBASE_TOKEN --non-interactive # prod build

notifications:
  email: # only receive email when the build status changes (someone broke the build!)
    on_failure: change
    on_success: change
